version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    #=====ローカルと本番切替=====
    #command: bundle exec puma -C config/puma.rb
    command: bundle exec puma -C config/puma.rb -e production
    #=========================
    volumes:
      - .:/monochords
      - public-data:/monochords/public
      - tmp-data:/monochords/tmp
      - log-data:/monochords/log
    #=====ローカルと本番切替=====
  #   depends_on:
  #     - db
  # db:
  #   image: mysql:5.7
  #   env_file:
  #     - ./environments/db.env
  #   volumes:
  #     - db-data:/var/lib/mysql
    #=========================
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/monochords/public
      - tmp-data:/monochords/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: