version: 2.1
jobs:
    rspec:
        docker:
            - image: circleci/ruby:2.7.1-node
              environment:
                    - BUNDLER_VERSION: 2.2.17
                    - RAILS_ENV: test
            - image: circleci/mysql:5.7
              environment:
                    - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
                    - MYSQL_ROOT_HOST: '%'

        working_directory: ~/monochords

        steps:
            - checkout

            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "Gemfile.lock" }}
                    - v1-dependencies-

            - run: mv config/database.yml.ci config/database.yml

            - run:
                name: install dependencies
                command: |
                        gem install bundler -v 2.2.17
                        bundle install --jobs=4 --retry=3 --path vendor/bundle

            - save_cache:
                    paths:
                        - ./vendor/bundle
                    key: v1-dependencies-{{ checksum "Gemfile.lock" }}

            - run:
                    name: Databasesetup
                    command: |
                        bundle exec rails db:create RAILS_ENV=test
                        bundle exec rails db:schema:load RAILS_ENV=test

            - run:
                name: yarn Install
                command: yarn install
            - run: bundle exec bin/webpack
            - run:
                name: RSpec
                command: bundle exec rspec

    deploy:
        machine:xs
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - 47:5e:3c:eb:7e:1a:d4:0f:25:e9:a2:43:8e:03:62:8e
            - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/monochords/deploy-me.sh"
 

workflows:
    version: 2.1
    rspec_and_deploy_workflow:
        jobs:
            - rspec
            - deploy:
                requires:
                    - rspec
                filters:
                    branches:
                        only: master
